### ISSUE TITLE
categories have empty list item

### ISSUE THREAD

**Issue by draeath** [bchetty/jekyllBasicBlog#1]
In _layouts/post.html, it looks like there's something wrong with the loop logic here. Rather than try to explain, I'll just show you. This is from your example site. I'm afraid I'm too new to this syntax to know what's going on - but I suspect there's an empty data element inside `site.categories`

The generated HTML (cleaned up whitespace only) - note the first list element is visually blank.

```
<div class="panel-body">
    <ul>
        <li><a href="/jekyllBasicBlog"></a></li>
        <li><a href="/jekyllBasicBlog/blog/post1">Post1</a></li>
    </ul>
</div>
```

![2016-08-09_2128](https://cloud.githubusercontent.com/assets/987449/17538982/4b5b07b6-5e78-11e6-9163-da770d2bb452.png)

**Comment by bchetty** [comment]
@draeath 

After your email, I worked on this and found that the first item in the list of categorized posts is always the 'name' of the category and not the post. You might understand it better, if you look at the code changes in [my last commit to this project repository](https://github.com/bchetty/jekyllBasicBlog/commit/e0e42f3806565742ba45da990dfff7c0a993573a).

This is corrected now. Please update your sources from my last commit to this project. If you have any more questions, please don't hesitate to shoot! :)

Thanks for reporting this problem and thanks for your patience! 👍

**Comment by bchetty** [comment]
By the way, this [comment on StackOverflow](http://stackoverflow.com/questions/20872861/jekyll-display-posts-by-category#comment33913326_20872918) helped me resolve the issue pretty fast (since your last contact with me).
